### ISSUE TITLE
drizzle:generate fails to run

### ISSUE THREAD

**Issue by faribauc** [alex8088/electron-toolkit#13]
### Describe the bug

Hi!

I have an electron/drizzle app with the following config:

drizzle.config.ts
```ts
import type { Config } from 'drizzle-kit'
import { DatabaseConfig } from './src/libs/config'

export default {
  schema: './database/schema.ts',
  out: './database/migrations',
  driver: 'better-sqlite',
  dbCredentials: {
    url: DatabaseConfig.databaseName
  },
  verbose: true,
  strict: true
} satisfies Config
```
config.ts
```ts
import path from 'path'
import { app } from 'electron'
import { is } from '@electron-toolkit/utils'

const databaseFileName = 'database.db'
export const defaultDatabaseName =
  !app || is.dev ? databaseFileName : path.join(app.getPath('userData'), databaseFileName)
export const databaseName = process.env.VITE_DATABASE_NAME || defaultDatabaseName

export const DatabaseConfig = {
  databaseName: databaseName
}
```
When I run `drizzle:generate` I get the following error:
```
/home/<user>/.nvm/versions/node/v21.7.1/bin/npm run drizzle:generate

> <project>@1.0.0-alpha20 drizzle:generate
> drizzle-kit generate:sqlite

drizzle-kit: v0.20.14
drizzle-orm: v0.30.6

No config path provided, using default 'drizzle.config.ts'
Reading config file '/home/<user>/path/to/<project>/drizzle.config.ts'
/home/<user>/path/to/<project>/node_modules/@electron-toolkit/utils/dist/index.cjs:6
  dev: !electron.app.isPackaged
                     ^

TypeError: Cannot read properties of undefined (reading 'isPackaged')
    at Object.<anonymous> (/home/<user>/path/to/<project>/node_modules/@electron-toolkit/utils/dist/index.cjs:6:22)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Object.newLoader (/home/<user>/path/to/<project>/node_modules/drizzle-kit/bin.cjs:8648:13)
    at extensions..js (/home/<user>/path/to/<project>/node_modules/drizzle-kit/bin.cjs:11176:28)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/<user>/path/to/<project>/src/libs/config.ts:3:20)

Node.js v21.7.1

Process finished with exit code 1
```
I created PR #12 as a possible solution.

Any thoughts?

### Electron-Toolkit Version

3.0.0

### Electron Version

28.2.0

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-toolkit/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-toolkit/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-toolkit#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-toolkit/issues) that reports the same bug to avoid creating a duplicate.

**Comment by KillerCodeMonkey** [comment]
i do not think this is a bug... i mean you are using an electron package inside of a node script that is called outside of electron.

just use your process.env.VITE_DATABASE_NAME || defaultDatabaseName in that file and when you init the db in your electron context override the name if not dev.

**Comment by faribauc** [comment]
It is an issue because the `electron` variable behaves differently when running in dev mode (missing the `app` property) and when running in compiled mode. It has nothing to do with how I get the database name.

Also, I can't define the VITE_DATABASE_NAME on a customer computer. The db file needs to be created by the app, on launch, in the `userData` directory. But that needs to happen only when running the compiled app, not in dev mode because in dev mode, the `app` variable does not exist, and I can't get the `userData` directory value. That is also the mode in which `drizzle:generate` runs in within the electron project.

In this specific case, failing to check if `electron.app` exists prior to check for `isPackaged` is the exact issue.

**Comment by SaidbekAbdiganiev** [comment]
I encountered a similar issue, although I wasn't using Drizzle in my application. In my case, the error was caused by the `ELECTRON_RUN_AS_NODE` environment variable. When this variable is set, it forces Electron to use the Node.js version installed on your system instead of Electron's built-in Node.js runtime ([link](https://www.electronjs.org/docs/latest/api/environment-variables#electron_run_as_node)). Can you try unsetting it or was there a specific reason to do this? I tried looking into Electron's documentation about dev mode removing `app` property, but seems like this is not the case.

**Comment by faribauc** [comment]
@SaidbekAbdiganiev Thanks for your feedback. It has no effect since this happens when running drizzle, not when running the electron app. That's when the check fails, the electron app does not exist. And that's why the `is.dev` check is failing. It assumes the `app` exists.

**Comment by Jimmy-sheep** [comment]
Maybe this answer is too late, but try this...
```shell
npm exec electron ./node_modules/drizzle-kit/bin.cjs generate
```

**Comment by jbeckton** [comment]
I have a brand new vite react electron app. it loaded and would display the home screen until I installed your utils package. I have an out of the box app that does nothing but display a single react component and I have this same error.

```
TypeError: Cannot read properties of undefined (reading 'isPackaged')
    at Object.<anonymous> (VM126 C:\Users\User\Projects\Electron\my-data-tool-repo\node_modules\.pnpm\@electron-toolkit+utils@4.0.0_electron@38.1.2\node_modules\@electron-toolkit\utils\dist\index.cjs:6:22)
    at Object.<anonymous> (VM126 C:\Users\User\Projects\Electron\my-data-tool-repo\node_modules\.pnpm\@electron-toolkit+utils@4.0.0_electron@38.1.2\node_modules\@electron-toolkit\utils\dist\index.cjs:107:3)
    at Module._compile (VM61 loader:1714:14)
    at Module._extensions..js (VM61 loader:1848:10)
    at Module.load (VM61 loader:1448:32)
    at Module._load (VM61 loader:1270:12)
    at c._load (VM75 node_init:2:17993)
    at s._load (VM117 renderer_init:2:34480)
    at TracingChannel.traceSync (VM30 node:diagnostics_channel:322:14)
    at wrapModuleLoad (VM61 loader:244:24)
```

**Comment by jbeckton** [comment]
If I try and use the utils in my preload I get the error, if I remove them no error. If I set the ELECTRON_RUN_AS_NODE variable to anything then the utils blow up everywhere and the app will not start at all.
